# Generated by Django 4.1.1 on 2022-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=20)),
                ('number_of_bedroom', models.IntegerField(blank=True, null=True)),
                ('number_of_bathroom', models.IntegerField(blank=True, null=True)),
                ('property_size', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Property Listings',
            },
        ),
    ]
