# Generated by Django 4.1.1 on 2022-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_size',
            new_name='lot_size',
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
