# Generated by Django 4.1.1 on 2022-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_property_size_property_lot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
