# Generated by Django 4.1.1 on 2022-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, default='static/images/larkspur.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, default='static/images/larkspur.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, default='static/images/larkspur.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, default='static/images/larkspur.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
