# Generated by Django 4.1.1 on 2022-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_property_photo_1_alter_property_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, default='Picture', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, default='Picture', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, default='Picture', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, default='Picuture', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
