# Generated by Django 4.1.1 on 2022-09-10 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_property_photo_5_property_photo_6_property_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
