# Generated by Django 4.1.1 on 2022-09-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_property_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
    ]
