# Generated by Django 4.1.1 on 2022-09-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_property_photo_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
    ]
